'use client';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { Waves, LayoutDashboard, FolderOpen, BookOpen, ChevronDown, ArrowUpRight, MapPin, Download, SlidersHorizontal, RotateCcw, Info, Play, Pause, ArrowRight, Droplets, CloudRain, ShieldCheck, Clock3, Users, Route, House, Sparkles, Send, X, Check, LoaderCircle, SkipBack, MoreHorizontal, AlertTriangle, Mountain, ExternalLink, CheckCheck } from 'lucide-react';
import { basins, defaults, ScenarioParams, simulate, SimulationResult, metricsAt } from '@/lib/simulation';
import type { LayerState } from './basin-map';
const BasinMap=dynamic(()=>import('./basin-map'),{ssr:false,loading:()=> <div className="map-loading"><Waves size={30}/><span>Preparing basin terrain…</span></div>});
type SavedScenario={id:number;name:string;parameters:ScenarioParams;result:SimulationResult;createdAt:string};
type Message={role:'user'|'assistant';text:string;disclaimer?:string};
export default function Dashboard(){
  const [params,setParams]=useState<ScenarioParams>(defaults),[active,setActive]=useState<ScenarioParams>(defaults),[result,setResult]=useState<SimulationResult>(()=>simulate(defaults));
  const [minute,setMinute]=useState(30),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[running,setRunning]=useState(false),[terrain,setTerrain]=useState(true);
  const [layers,setLayers]=useState<LayerState>({settlements:true,roads:true,bridges:true,schools:true,hospitals:true,river:true,flood:true});
  const [modal,setModal]=useState<'history'|'docs'|'assistant'|'export'|null>(null),[history,setHistory]=useState<SavedScenario[]>([]),[historyLoading,setHistoryLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [question,setQuestion]=useState(''),[messages,setMessages]=useState<Message[]>([]),[asking,setAsking]=useState(false),[hasRun,setHasRun]=useState(false);
  const chatEnd=useRef<HTMLDivElement>(null);
  const metrics=metricsAt(result,minute),dirty=JSON.stringify(params)!==JSON.stringify(active);
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>setMinute(t=>{if(t>=60){setPlaying(false);return 60}return Math.min(60,t+1)}),650/speed);return()=>clearInterval(timer)},[playing,speed]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer)},[notice]);
  useEffect(()=>{chatEnd.current?.scrollIntoView({behavior:'smooth'})},[messages,asking]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')setModal(null)};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener)},[]);
  async function run(){setRunning(true);setError('');setPlaying(false);try{const response=await fetch('/api/scenarios',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parameters:params})});const data=await response.json();if(!response.ok)throw new Error(data.error);setActive({...data.parameters});setResult(data.result);setMinute(0);setPlaying(true);setHasRun(true);setMessages([]);setNotice('Simulation created and saved to your scenarios.');}catch(e){setError(e instanceof Error?e.message:'Simulation failed.')}finally{setRunning(false)}}
  async function openHistory(){setModal('history');setHistoryLoading(true);setError('');try{const response=await fetch('/api/scenarios');const data=await response.json();if(!response.ok)throw new Error(data.error);setHistory(data)}catch(e){setError(e instanceof Error?e.message:'Unable to load scenarios.')}finally{setHistoryLoading(false)}}
  function loadScenario(s:SavedScenario){setParams(s.parameters);setActive(s.parameters);setResult(s.result);setMinute(30);setPlaying(false);setHasRun(true);setMessages([]);setModal(null);setNotice('Saved scenario loaded.');}
  async function ask(text:string){if(!text.trim()||asking)return;setQuestion('');setMessages(m=>[...m,{role:'user',text}]);setAsking(true);try{const response=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parameters:active,question:text})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessages(m=>[...m,{role:'assistant',text:data.answer,disclaimer:data.disclaimer}]);}catch{setMessages(m=>[...m,{role:'assistant',text:'The briefing could not be generated. Please try again.'}])}finally{setAsking(false)}}
  function exportReport(format:'json'|'csv'){const content=format==='json'?JSON.stringify({name:'RiverTwin scenario report',parameters:active,result,timeMinute:minute,currentImpact:metrics,disclaimer:'Illustrative physically inspired model. Not for operational emergency decisions.'},null,2):'Settlement,Population,Arrival (min),Modeled depth (m)\n'+result.settlements.map(s=>`${s.name},${s.population},${s.arrival},${s.depth}`).join('\n');const blob=new Blob([content],{type:format==='json'?'application/json':'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`rivertwin-${active.river.toLowerCase().replaceAll(' ','-')}.${format}`;a.click();URL.revokeObjectURL(url);setModal(null);setNotice('Simulation report exported.');}
  const change=(key:keyof ScenarioParams,value:number|string)=>setParams(p=>({...p,[key]:value}));
  return <div className="app-shell">
    <header className="topbar"><a className="brand" href="/" aria-label="RiverTwin home"><div className="brand-icon"><Waves size={26} strokeWidth={2.1}/></div><span>River<span>Twin</span><small>SEE THE RISK. ACT EARLIER.</small></span></a><nav><button className="nav-item active" onClick={()=>setModal(null)}><LayoutDashboard size={16}/> Workspace</button><button className={'nav-item '+(modal==='history'?'nav-selected':'')} onClick={openHistory}><FolderOpen size={17}/> Scenarios</button><button className="nav-item" onClick={()=>setModal('docs')}><BookOpen size={16}/> Documentation <ArrowUpRight size={13}/></button></nav><div className="topbar-right"><span className="prototype-badge"><i/> Prototype v0.1</span><span className="header-divider"/><button className="profile" title="About this workspace" onClick={()=>setModal('docs')}>AS</button></div></header>
    <section className="workspace-heading"><div><div className="eyebrow">DISASTER RESILIENCE WORKSPACE <span>/</span> NEPAL</div><h1>Flood & Dam-Break Digital Twin <span className="beta-tag">BETA</span></h1><p>Simulate the flood. Understand the impact. Make time to act.</p></div><div className="workspace-actions"><span className="basin-location"><MapPin size={15}/>{active.river.replace(' River','')} basin, Nepal</span><button className="secondary-button" onClick={()=>setModal('export')}><Download size={15}/> Export report</button></div></section>
    <main className="workspace-grid">
      <aside className="scenario-panel"><div className="panel-heading"><span><SlidersHorizontal size={17}/> Scenario setup</span><button className="icon-button" title="Reset scenario" onClick={()=>{setParams(defaults);setNotice('Scenario inputs reset to defaults.')}}><RotateCcw size={15}/></button></div>
      <div className="scenario-scroll"><div className="scenario-preset"><span className="preset-icon"><Waves size={17}/></span><div><b>Dam-break scenario</b><small>Build your what-if</small></div><span className="draft-tag">{dirty?'Edited':'Draft'}</span></div>
      <div className="field-group"><label htmlFor="river">River basin <Info size={13}/></label><div className="select-wrap"><Waves size={15}/><select id="river" value={params.river} onChange={e=>setParams(p=>({...p,river:e.target.value,source:basins[e.target.value].source}))}>{Object.keys(basins).map(r=><option key={r}>{r}</option>)}</select><ChevronDown size={14}/></div></div>
      <div className="field-group"><label htmlFor="source">Dam / lake <Info size={13}/></label><div className="select-wrap"><Mountain size={15}/><select id="source" value={params.source} onChange={e=>change('source',e.target.value)}><option>{basins[params.river].source}</option><option>Hypothetical upstream reservoir</option></select><ChevronDown size={14}/></div><small className="field-help"><MapPin size={11}/> {params.river==='Melamchi River'?'Upper Melamchi catchment':params.river==='Dudh Koshi River'?'Khumbu high mountain catchment':'Langtang valley catchment'}</small></div>
      <div className="section-rule"/>
      <div className="range-field"><label htmlFor="volume"><span><Droplets size={14}/> Water volume</span><Info size={13}/></label><div className="range-value"><b>{params.volume.toFixed(1)}</b><span>million m³</span></div><input id="volume" type="range" min="0.5" max="20" step="0.5" value={params.volume} style={{'--range':`${(params.volume-.5)/19.5*100}%`} as React.CSSProperties} onChange={e=>change('volume',Number(e.target.value))}/><div className="range-labels"><span>0.5 M m³</span><span>20 M m³</span></div></div>
      <div className="range-field"><label htmlFor="breach"><span><Route size={14}/> Breach width</span><Info size={13}/></label><div className="range-value"><b>{params.breach}</b><span>meters</span></div><input id="breach" type="range" min="5" max="100" step="5" value={params.breach} style={{'--range':`${(params.breach-5)/95*100}%`} as React.CSSProperties} onChange={e=>change('breach',Number(e.target.value))}/><div className="range-labels"><span>5 m</span><span>100 m</span></div></div>
      <div className="range-field rain-field"><label htmlFor="rainfall"><span><CloudRain size={14}/> Rainfall intensity</span><Info size={13}/></label><div className="range-value"><b>{params.rainfall}</b><span>mm / hour</span></div><input id="rainfall" type="range" min="0" max="100" step="5" value={params.rainfall} style={{'--range':`${params.rainfall}%`} as React.CSSProperties} onChange={e=>change('rainfall',Number(e.target.value))}/><div className="range-labels"><span>No rain</span><span>Extreme</span></div><div className="rain-status"><span/>{params.rainfall===0?'Dry conditions':params.rainfall<20?'Light rainfall':params.rainfall<50?'Moderate rainfall':params.rainfall<75?'Heavy rainfall':'Extreme rainfall'}<span className="rain-bars">▂ ▄ ▆ <em>█</em></span></div></div>
      <div className="model-note"><Info size={15}/><p>A simplified, physically inspired model for exploration. <button onClick={()=>setModal('docs')}>How it works <ArrowUpRight size={11}/></button></p></div></div>
      <div className="run-section">{error&&<p className="error-text">{error}</p>}<button className="run-button" onClick={run} disabled={running}>{running?<LoaderCircle className="spin" size={17}/>:<Play size={15} fill="currentColor"/>}{running?'Running simulation…':'Run simulation'}<ArrowRight size={17}/></button><span><ShieldCheck size={12}/> Safe to explore. Powerful to prepare.</span></div></aside>
      <section className="map-section"><BasinMap params={active} result={result} minute={minute} layers={layers} setLayers={setLayers} terrain={terrain} setTerrain={setTerrain}/><div className="timeline"><div className="timeline-top"><div><Clock3 size={15}/><b>Simulation timeline</b><span className="time-badge">T + {String(minute).padStart(2,'0')} min</span></div><span className="timeline-hint">{playing?'Flood propagation in progress':'Drag to explore flood propagation'}</span><button className="speed-button" onClick={()=>setSpeed(s=>s===4?1:s*2)} title="Change playback speed">{speed}× <ChevronDown size={11}/></button></div><div className="timeline-bottom"><button className="play-button" aria-label={playing?'Pause simulation':'Play simulation'} onClick={()=>{if(minute===60)setMinute(0);setPlaying(!playing)}}>{playing?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}</button><button className="rewind-button" aria-label="Rewind simulation" onClick={()=>{setMinute(0);setPlaying(false)}}><SkipBack size={15}/></button><div className="timeline-track"><input aria-label="Simulation time in minutes" type="range" min="0" max="60" value={minute} onChange={e=>{setMinute(Number(e.target.value));setPlaying(false)}} style={{'--range':`${minute/60*100}%`} as React.CSSProperties}/><div className="timeline-ticks">{[0,10,20,30,40,50,60].map(t=><button key={t} className={minute===t?'current':''} onClick={()=>{setMinute(t);setPlaying(false)}}>T+{t}</button>)}</div></div><span className="duration">60<small>min</small></span></div></div></section>
      <aside className="impact-panel"><div className="panel-heading"><span><LayoutDashboard size={16}/> Impact overview</span><span className="live-badge"><i/> LIVE</span></div><div className="impact-scroll"><div className="impact-context"><span>At T + {minute} minutes</span><span className="risk-badge">{metrics.depth>=3?'HIGH':metrics.depth>0?'MODERATE':'NO'} IMPACT</span></div><div className="depth-card"><div><Droplets size={16}/><span>Maximum flood depth</span><Info size={13}/></div><strong>{metrics.depth.toFixed(1)}<span>m</span><svg viewBox="0 0 90 32"><path d="M0 28 L12 25 L22 26 L31 18 L39 22 L49 11 L59 15 L68 5 L79 9 L89 1"/></svg></strong><small><span className="coral-dot"/>{metrics.depth>=3?'Severe inundation potential':metrics.depth>0?'Inundation developing':'Awaiting flood arrival'}</small></div>
      <div className="impact-metric settlement-metric"><div className="metric-icon orange"><House size={18}/></div><div><span>First settlement impacted</span><strong>{result.settlements[0].name}<span className="small-tag">{minute>=result.settlements[0].arrival?'Impacted':'At risk'}</span></strong></div></div>
      <div className="impact-metric"><div className="metric-icon amber"><Clock3 size={18}/></div><div><span>Estimated first arrival</span><strong>{result.settlements[0].arrival}<small>min</small></strong></div><span className="metric-hint">after breach</span></div>
      <div className="impact-metric"><div className="metric-icon pink"><Users size={18}/></div><div><span>Population at risk</span><strong>{metrics.population.toLocaleString()}<small>people</small></strong></div></div>
      <div className="impact-metric"><div className="metric-icon lavender"><Route size={18}/></div><div><span>Road segments affected</span><strong>{metrics.roads}<small>segments</small></strong></div></div>
      <button className="detail-link" onClick={()=>setModal('export')}>View detailed impact report <ArrowUpRight size={13}/></button>
      <div className="assistant-card"><div className="assistant-heading"><span><Sparkles size={17}/> RiverTwin assistant</span><span>AI PREVIEW</span></div><h3>From simulation<br/>to smarter action.</h3><p>Understand who is at risk and where to act first.</p><button onClick={()=>{setModal('assistant');if(!messages.length)ask('Which settlements should evacuate first?')}}><span>Which settlements should<br/>evacuate first?</span><ArrowUpRight size={15}/></button><div className="assistant-footer"><span className="assistant-dot"/> Grounded in your scenario</div></div>
      <div className="impact-disclaimer"><Info size={13}/><p>Indicative estimates, not official forecasts. Always follow local emergency guidance.</p></div></div><div className="result-status"><CheckCheck size={13}/>{hasRun?'Scenario saved to workspace':'Example scenario loaded'}<span>•</span> 60 min window</div></aside>
    </main><footer className="app-footer"><span><span className="status-dot"/> All systems operational <span className="footer-divider">|</span> Built for a more resilient Nepal <span>🇳🇵</span></span><span>Illustrative exposure data <span className="footer-divider">·</span> WGS 84 / EPSG:4326 <button onClick={()=>setModal('docs')}>About the model <ArrowUpRight size={11}/></button></span></footer>
    {notice&&<div className="toast"><Check size={17}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
    {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><section className={'modal '+(modal==='assistant'?'chat-modal':'')} role="dialog" aria-modal="true" aria-label={modal==='history'?'Saved scenarios':modal==='docs'?'Model documentation':modal==='export'?'Impact report':'RiverTwin assistant'} onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">RIVERTWIN WORKSPACE</span><h2>{modal==='history'?'Your scenarios':modal==='docs'?'A model for better questions.':modal==='export'?'Scenario impact report':'Your evacuation briefing'}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={()=>setModal(null)}><X size={20}/></button></div>
      {modal==='history'&&<div className="modal-body"><p className="muted">Revisit saved runs and explore the decisions behind them.</p>{historyLoading?<div className="empty-state"><LoaderCircle className="spin"/>Loading scenarios…</div>:error?<p className="error-text">{error}</p>:!history.length?<div className="empty-state"><FolderOpen size={35}/><h3>Your first scenario starts here.</h3><p>Adjust the parameters and run a simulation. Each run is saved automatically.</p><button className="run-button" onClick={()=>setModal(null)}>Build a scenario <ArrowRight size={16}/></button></div>:<div className="history-list">{history.map(s=><button key={s.id} onClick={()=>loadScenario(s)}><span className="history-icon"><Waves size={21}/></span><div><b>{s.name}</b><p>{s.parameters.volume}M m³ · {s.parameters.breach} m breach · {s.parameters.rainfall} mm/h</p><small>{new Date(s.createdAt).toLocaleString()}</small></div><ArrowUpRight size={18}/></button>)}</div>}</div>}
      {modal==='docs'&&<div className="modal-body documentation"><span className="doc-badge"><Mountain size={15}/> HACKATHON PROTOTYPE · v0.1</span><p>RiverTwin helps you explore how an upstream dam or lake breach could affect communities in a Nepal river basin.</p><h3>How the simulation works</h3><p>Water volume and breach width determine a relative flood severity. Rainfall increases that severity, while wave speed scales with its square root. A widening corridor follows an illustrative river centerline over a 60-minute window. Discharge uses a simplified broad-crested-weir relationship.</p><h3>What the map tells you</h3><p>The colored corridor is a conceptual inundation footprint, not a terrain-resolved hydraulic solution. Depth metrics are scenario-level estimates; the legend is an indicative color reference, not a depth raster. Infrastructure markers, populations, source locations, and arrival times are demonstration data.</p><h3>Explore a scenario</h3><ol><li>Select a basin and adjust water, breach, and rainfall inputs.</li><li>Run the simulation to save a scenario and animate propagation.</li><li>Scrub the timeline, toggle layers, and select settlements.</li><li>Use the assistant to review arrival-based evacuation priorities.</li></ol><div className="doc-warning"><AlertTriangle size={21}/><p><b>Not an early-warning system.</b> The assistant is a deterministic, model-grounded briefing tool, not a live language model. No real-time sensors, validated elevation solver, or official exposure inventory are connected. Follow Nepal DHM and local authorities for emergency action.</p></div><a className="doc-link" href="https://www.dhm.gov.np/" target="_blank" rel="noreferrer">Nepal Department of Hydrology and Meteorology <ExternalLink size={14}/></a></div>}
      {modal==='export'&&<div className="modal-body"><div className="report-summary"><div><small>RIVER BASIN</small><b>{active.river}</b></div><div><small>PEAK DISCHARGE</small><b>{result.peakDischarge.toLocaleString()} m³/s</b></div><div><small>PLAYBACK TIME</small><b>T + {minute} min</b></div></div><p className="muted">Settlement exposure over the full modeled scenario</p><div className="report-table-wrap"><table><thead><tr><th>Settlement</th><th>Population</th><th>Arrival</th><th>Depth</th></tr></thead><tbody>{result.settlements.map(s=><tr key={s.name}><td>{s.name}</td><td>{s.population.toLocaleString()}</td><td>{s.arrival} min</td><td>{s.depth} m</td></tr>)}</tbody></table></div><p className="report-disclaimer"><Info size={15}/> Illustrative estimates. Not suitable for operational emergency decisions.</p><div className="export-buttons"><button className="secondary-button" onClick={()=>exportReport('csv')}><Download size={15}/> Download CSV</button><button className="run-button" onClick={()=>exportReport('json')}><Download size={15}/> Export full scenario</button></div></div>}
      {modal==='assistant'&&<><div className="chat-context"><span className="assistant-dot"/>{active.river} · {active.volume}M m³ · {active.breach} m breach</div><div className="chat-messages">{!messages.length&&<div className="empty-state"><Sparkles size={30}/><h3>Turn insight into a plan.</h3><p>Ask about evacuation priorities or infrastructure exposure in this scenario.</p></div>}{messages.map((m,i)=><div key={i} className={'chat-message '+m.role}>{m.role==='assistant'&&<span className="chat-avatar"><Sparkles size={16}/></span>}<div>{m.role==='assistant'&&<b>RiverTwin assistant</b>}<p>{m.text}</p>{m.disclaimer&&<small>{m.disclaimer}</small>}</div></div>)}{asking&&<div className="chat-thinking"><LoaderCircle size={16} className="spin"/> Reviewing modeled impacts…</div>}<div ref={chatEnd}/></div><div className="chat-prompts"><button disabled={asking} onClick={()=>ask('Which settlements should evacuate first?')}>Evacuation priorities <ArrowUpRight size={12}/></button><button disabled={asking} onClick={()=>ask('Which roads and critical facilities need attention?')}>Critical infrastructure <ArrowUpRight size={12}/></button></div><form className="chat-form" onSubmit={e=>{e.preventDefault();ask(question)}}><input aria-label="Ask about this scenario" placeholder="Ask about this scenario…" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)}/><button disabled={asking||!question.trim()} aria-label="Send question"><Send size={18}/></button></form><p className="chat-footnote">Model-grounded preview · Always verify with local authorities</p></>}
    </section></div>}
  </div>;
}
