import { chromium } from '@playwright/test';
const browser = await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader','--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',msg=>{if(msg.type()==='error')console.log('CONSOLE:',msg.text().slice(0,200));});
await page.goto('http://localhost:3000',{waitUntil:'domcontentloaded',timeout:60000});
await page.locator('.map-marker').first().waitFor({timeout:60000});
await page.locator('.map-shell[data-flood-ready="true"]').waitFor({timeout:60000});
await page.waitForTimeout(8000);
const mapBounds=await page.locator('.map-canvas').boundingBox();
if(!mapBounds || mapBounds.height<400)throw new Error('Map canvas collapsed: '+JSON.stringify(mapBounds));
console.log('Map dimensions:',mapBounds.width+' × '+mapBounds.height);
await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
console.log('Initial markers:',await page.locator('.map-marker').count());
await page.getByRole('button',{name:'Run simulation',exact:true}).click();
await page.getByText('Simulation created and saved to your scenarios.').waitFor();
await page.getByRole('button',{name:'Pause simulation'}).click();
await page.getByRole('button',{name:'T+30',exact:true}).click();
console.log('Population:',await page.locator('.impact-metric').allTextContents());
await page.getByRole('button',{name:'Which settlements should evacuate first?'}).click();
await page.locator('.chat-message.assistant').waitFor();
console.log('Briefing:',(await page.locator('.chat-message.assistant').textContent()).slice(0,150));
await page.getByRole('button',{name:'Close dialog'}).click();
await page.getByRole('button',{name:'Scenarios',exact:true}).click();
await page.locator('.history-list>button').first().waitFor();
console.log('Saved scenario count:',await page.locator('.history-list>button').count());
await page.locator('.history-list>button').first().click();
await page.getByLabel('Inundation zone').uncheck();
await page.getByLabel('Inundation zone').check();
await page.getByRole('button',{name:'Export report',exact:true}).click();
console.log('Report rows:',await page.locator('tbody tr').count());
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'Download CSV'}).click();
console.log('Export:',(await downloadPromise).suggestedFilename());
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(1000);
await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
console.log('Mobile overflow:',await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth));
console.log('Page errors:',errors);
await browser.close();
if(errors.length)process.exit(1);
